Commit #0012 (thekotekjournal/jgw)
Fix error:
[0] Compile: app/worker/util.cpp
File doesn't exist: FILES[0]
Error: Process completed with exit code 1.